### ISSUE TITLE
Not seeing context or namespace in my tmux status line

### ISSUE THREAD

**Issue by davidfic** [jonmosco/kube-tmux#5]
After following the instructions about cloning etc I do not see the kube context in my status bar. 

I'm using [this repo](https://github.com/gpakosz/.tmux) for my current tmux setup.

Not sure what other info you'd like me to provide to help debug this.

**Comment by jonmosco** [comment]
Can you show me the addition of the prompt to that code that you are using?  What does that status line config you applied look like?

**Comment by davidfic** [comment]
So being very new to configuring the tmux status line I kind of had to guess as what I needed to do. 

My right status looks like:

    tmux_conf_theme_status_right='#{prefix}#{pairing}  #{status-right} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b     | #{username}#{root} | #{hostname} '

**Comment by jonmosco** [comment]
Hmm, ok.  I do not see kube-tmux in there, are you sourcing it and referencing it somewhere else in your configuration ?

**Comment by davidfic** [comment]
Sorry here is the relevant part from my tmux.conf file

    set -g status-right "#(/bin/bash ~/.tmux/kube.tmux 250 red cyan)"

    bind e new-window -n '~/.tmux.conf.local' "sh -c '\${EDITOR:-vim} ~/.tmux.conf.local && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"

and in `tmux.conf.local`

    tmux_conf_theme_status_left=' ❐ #S | ↑#{?uptime_d, #{uptime_d}d,}#{?uptime_h, #{uptime_h}h,}#{?uptime_m, #{uptime_m}m,} '
    tmux_conf_theme_status_right='#{prefix}#{pairing} #{status-right} #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '

**Comment by jonmosco** [comment]
Can you try it out without the other customization?  Create a ~/.tmux.conf file that has the status-right to determine if this is related to that plugin, or to kube-tmux.

**Comment by davidfic** [comment]
So I've confirmed it is just the interaction with the tmux conf file I have. You can close this ticket as I'll have to debug on my side. 

Thanks.
